### ISSUE TITLE
QA Quest. Додаток WiDiQ/The "(Ім’я По Батькові) text is displayed in the "Завдання" section of the "Тест план" page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1413]
Steps to reproduce:

1. Open page https://www.qax-camp.com.ua/courses/widiq-test/lessons/widiq-test-plan/quizzes/%d1%82%d0%b5%d1%81%d1%82-%d0%bf%d0%bb%d0%b0%d0%bd/
2. Scroll down to the "Завдання" section of the "Тест план" page
3. Pay attention to the The "(Ім’я По Батькові) text in the "Завдання" section of the "Тест план" page

Actual Result: The "(Ім’я По Батькові) text is displayed in the "Завдання" section of the "Тест план" page

Expected Result: The "(Ім’я та Прізвище) text is displayed in the "Завдання" section of the "Тест план" page

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/9987570f-d93e-44a5-9d90-0040505eb014)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
Issue is still
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/37b22d6e-68cd-4513-b746-ac9c1f786816)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
