### ISSUE TITLE
Lessons "Ревью тестової документації"/D/ The name of author is in EN

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/qax-portal-2#1566]
**Steps to reproduce:**

1. Open page: https://www.qax-camp.com.ua/courses/testing/lessons/test-review/
2. Find a section of author
3. Look at the name of author

**Actual result:** The name of author is in EN
**Expected result:**  The name of author is in UA

**Additional information:** https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=390-12776&mode=design&t=iKQG0NIz9RDScf02-0

**Environment:**
Windows 10
Google Chrome v 117.0.5938.132

**Attachment:** 
![chrome_4EX5OJ81yN](https://github.com/scholokov/qax-portal-2/assets/126480322/0a0906f9-dc64-4bd4-ac5d-f0babf10df94)

**Comment by Aleksandrkobets99** [comment]
#1015

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
Issue is still
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/6e0624c1-cd74-43cd-91cf-68ed8bf81cbf)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
