### ISSUE TITLE
Lesson "IT Vocabulary – АйТі Сленг"/ Spaces are displayed on the right and left of "/" symbol in the Design definition

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#1881]
**Steps to Reproduce:**

1. Open page https://www.qax-camp.com.ua/courses/processes/lessons/it-vocabulary/
2. Pay attention to the Spaces on the right and left of "/" symbol in the Design definition

**Actual Result**: Spaces are displayed on the right and left of "/" symbol in the Design definition

**Expected Result:** Spaces are not displayed on the right and left of "/" symbol in the Design definition

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/0f5ffe96-56a6-4068-a811-23d46bf58208)

**Comment by ODrobik** [comment]
#938

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
Issue still exist 
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/b3fc85ab-6435-430c-b644-d986ed0fe4fa)
