### ISSUE TITLE
In the "Практика" section of the "Як все відбувається" point, some headings have a font size of 36 px

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/qax-portal-2#1996]
Steps to reproduce:
1. Open the page https://www.qax-camp.com.ua/practice-team/
2. Scroll to the "Як все відбувається" point and Click on it
3. Pay attention to the font size of the headings

Actual result:
1. Some headings have a font size of 36 px
2. Some headings have a font size of 21 px

Expected result:
1. The headings have the same font size 21px 

Attachments:
<img width="1280" alt="Снимок экрана 2024-02-08 в 15 22 31" src="https://github.com/scholokov/qax-portal-2/assets/130754297/d5616b31-6fb2-4a85-af1d-3cf724f6f1f7">
<img width="1280" alt="Снимок экрана 2024-02-08 в 15 17 58" src="https://github.com/scholokov/qax-portal-2/assets/130754297/27d1598b-a67f-4fae-a088-9475a9818b86">

Documentation:
[Figma](https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Portal-design?type=design&node-id=5133-709&mode=design&t=34k2AJzUPTKminuZ-0) 
[Requirements](https://github.com/scholokov/qax-portal-2/wiki/1.0.4.-Practice)

Environment:
Browser: Google Chrome 121.0.6167.160 
OS: macOS 11.7.10

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/qax-portal-2/assets/88647733/5e487af4-1770-49e1-ac56-68d5fb41c911)

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
The headings still have the wrong font size 24px.
The headings should have the same font size 21px.
And the headings don't need the tag <strong>
![Снимок экрана 2024-02-16 в 18 03 38](https://github.com/scholokov/qax-portal-2/assets/130754297/ba5437cd-ed67-43df-852e-2044ee3eafe5)
![Снимок экрана 2024-02-16 в 18 16 37](https://github.com/scholokov/qax-portal-2/assets/130754297/bcb687fb-551c-4204-9952-680aed2be134)
[New Figma link](https://www.figma.com/file/2JlqZybc4fOvZcPT7oiqrg/Portal-design?type=design&node-id=5133-709&mode=design&t=IoqfSE2zK5SUgwft-0)
