### ISSUE TITLE
Interview - The "Тестова співбесіда 2023.11.20" video is displayed in the "Інтерв’ю – 04.12.2023"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2197]
Steps to Reproduce:
1. Open page https://www.qax-camp.com.ua/courses/interview/lessons/test-interview/
2. Pay attention to the video of the "Інтерв’ю – 04.12.2023" in the "Тестова співбесіда"

Actual Result:
The "Тестова співбесіда 2023.11.20" video is displayed in the "Інтерв’ю – 04.12.2023"
Expected Result:
The "Тестова співбесіда 2023.12.04" video is displayed in the "Інтерв’ю – 04.12.2023"

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/da2f7ec8-b485-41cb-92dc-aaebe0abdb30)

**Comment by ODrobik** [comment]
#1773

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
The issue is still
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/d3e253a0-4423-4a14-ad26-1beb341d283d)

**Comment by ODrobik** [comment]
Open new issue #2226
