### ISSUE TITLE
Achievements - QUEST/ The "Web - QDQ"  is displayed  of the Web + mobile technical block

### ISSUE THREAD

**Issue by ODrobik** [scholokov/qax-portal-2#2199]
**Steps to Reproduce:**
1. Open page https://www.qax-camp.com.ua/ach-quest-all-by-topics/
2. Pay attention to the text of tooltip in the direction of the Web + mobile technical block

**Actual Result:**
The "Web - **QDQ**" text of tooltip is displayed  of the Web + mobile technical block

**Expected Result:** 
The "Web - **WDQ**" text of tooltip  is displayed  of the Web + mobile technical block

**Environment:**
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

**Attachment:**
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/bd6838f7-b6dc-438a-86d0-61b58d48ba1f)

**Comment by ODrobik** [comment]
#2054

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
Issue is still
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/96bf665e-7d56-4858-9f6f-66ea7241d0ed)

**Comment by scholokov** [comment]
не зрозумів у чому проблема

**Comment by ODrobik** [comment]
Додано деталей до Актуального та Очікуваного результатів

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
