### ISSUE TITLE
Achievements/The distance between the body and the footer is 0px in the "Досягнення – Проєкти" 

### ISSUE THREAD

**Issue by GNatala** [scholokov/qax-portal-2#2278]
**Steps to reproduce:**

1. Open https://www.qax-camp.com.ua/ach-project-all-by-project/
2. Pay attention to the distance between the body and the footer.

**Actual result:**
The distance between the body and the footer is 0px in the "Досягнення – Проєкти" .

**Expected result:**
The distance between the body and the footer is more than 100px in the "Досягнення – Проєкти" .

**Environment:**
Windows 10
Google Chrome v 125.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/user-attachments/assets/783e811b-9ef1-4cf4-8378-e8333d1160d4)

**Comment by GNatala** [comment]
#2230

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
The issue still exists.
![image](https://github.com/user-attachments/assets/34be2507-0734-4a80-a142-5edf1971ad2b)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
